import { Weapon, WeaponType, Helmet, Armor, Spell, SpellType, LevelConfig, EnvironmentType } from './types';

export const DEFAULT_WEAPONS: Weapon[] = [
  {
    id: 'w_basic_bow',
    name: 'Training Wood Bow',
    type: WeaponType.BOW,
    damage: 35,
    speedMultiplier: 1.0,
    gravityMultiplier: 1.0,
    cost: 0,
    unlocked: true,
    description: 'A simple flexible bow. Standard range and damage.',
  },
  {
    id: 'w_elven_bow',
    name: 'Long Elven Bow',
    type: WeaponType.BOW,
    damage: 55,
    speedMultiplier: 1.3,
    gravityMultiplier: 0.75,
    cost: 180,
    unlocked: false,
    description: 'Lightweight and sleek. Shoots arrows at high speeds with flatter trajectories.',
  },
  {
    id: 'w_dragon_bow',
    name: 'Dragon Fire Bow',
    type: WeaponType.BOW,
    damage: 85,
    speedMultiplier: 1.5,
    gravityMultiplier: 0.65,
    cost: 500,
    unlocked: false,
    description: 'Forged from red dragon scales. Releases burning arrows of cataclysmic damage.',
  },
  {
    id: 'w_hunter_spear',
    name: 'Hunter Spear',
    type: WeaponType.SPEAR,
    damage: 65,
    speedMultiplier: 0.85,
    gravityMultiplier: 1.4,
    cost: 100,
    unlocked: false,
    description: 'Thick wooden throwing spear. High parabolic arc, but inflicts severe torso damage.',
  },
  {
    id: 'w_barbarian_spear',
    name: 'Steel Barbarian Spear',
    type: WeaponType.SPEAR,
    damage: 100,
    speedMultiplier: 1.0,
    gravityMultiplier: 1.25,
    cost: 350,
    unlocked: false,
    description: 'Reinforced heavy steel spearhead. Can instantly pierce most defenses.',
  },
  {
    id: 'w_shuriken',
    name: 'Iron Shurikens',
    type: WeaponType.SHURIKEN,
    damage: 25,
    speedMultiplier: 1.6,
    gravityMultiplier: 0.45,
    cost: 140,
    unlocked: false,
    description: 'Fires swift ninja stars in a flat, rapid arc. High attack rate.',
  },
  {
    id: 'w_golden_star',
    name: 'Golden Ninja Star',
    type: WeaponType.SHURIKEN,
    damage: 40,
    speedMultiplier: 1.85,
    gravityMultiplier: 0.35,
    cost: 400,
    unlocked: false,
    description: 'Sacred gold-rimmed shurikens of the high order. Extremely fast and deadly.',
  },
];

export const DEFAULT_HELMETS: Helmet[] = [
  {
    id: 'h_none',
    name: 'Bare Head',
    defense: 1.0,
    durability: 0,
    cost: 0,
    unlocked: true,
    visualType: 'none',
    description: 'No headgear. Headshots will deal 3.0x standard damage!',
  },
  {
    id: 'h_viking',
    name: 'Viking Horns',
    defense: 0.5,
    durability: 1,
    cost: 120,
    unlocked: false,
    visualType: 'viking',
    description: 'Horned iron helmet. Completely blocks the first headshot and flies off.',
  },
  {
    id: 'h_knight',
    name: 'Knight Sallet',
    defense: 0.3,
    durability: 2,
    cost: 260,
    unlocked: false,
    visualType: 'knight',
    description: 'Durable templar visor. Absorbs up to 2 headshots with high damage reduction.',
  },
  {
    id: 'h_wizard',
    name: 'Archmage Hat',
    defense: 0.6,
    durability: 1,
    cost: 180,
    unlocked: false,
    visualType: 'wizard',
    description: 'Magically imbued hat. Passively increases spell cooldown recovery rates by 25%.',
  },
  {
    id: 'h_crown',
    name: 'Monarch Crown',
    defense: 0.2,
    durability: 3,
    cost: 600,
    unlocked: false,
    visualType: 'crown',
    description: 'Splendid golden crown. Offers royal tier defense and breaks only after 3 headshots.',
  },
];

export const DEFAULT_ARMORS: Armor[] = [
  {
    id: 'a_none',
    name: 'Training Jerkin',
    extraHealth: 0,
    cost: 0,
    unlocked: true,
    visualColor: '#3a3a3a',
    description: 'Standard black stickman tunic. 100 Base HP.',
  },
  {
    id: 'a_leather',
    name: 'Hardened Leather Vest',
    extraHealth: 25,
    cost: 150,
    unlocked: false,
    visualColor: '#7c4b1b',
    description: 'Thick hide jacket that buffs maximum health by 25 points.',
  },
  {
    id: 'a_chainmail',
    name: 'Knight Chainmail',
    extraHealth: 50,
    cost: 300,
    unlocked: false,
    visualColor: '#7a8b99',
    description: 'Woven steel link underlayer. Boosts maximum health by 50 points.',
  },
  {
    id: 'a_dragon',
    name: 'Dragon Scale Armor',
    extraHealth: 100,
    cost: 650,
    unlocked: false,
    visualColor: '#a62424',
    description: 'Forged in volcanic fire. Bestows +100 bonus health.',
  },
];

export const DEFAULT_SPELLS: Spell[] = [
  {
    id: 's_fire',
    name: 'Flame Arrow',
    type: SpellType.FIRE,
    cooldown: 3,
    duration: 4,
    cost: 150,
    unlocked: false,
    description: 'Infuses your next projectile with flames, causing fire damage over time.',
  },
  {
    id: 's_ice',
    name: 'Frost Touch',
    type: SpellType.ICE,
    cooldown: 4,
    duration: 3,
    cost: 200,
    unlocked: false,
    description: 'Coats your ammunition in ice. Freezes the enemy, significantly delaying their rate of fire.',
  },
  {
    id: 's_shield',
    name: 'Aegis Bubble',
    type: SpellType.SHIELD,
    cooldown: 5,
    duration: 5,
    cost: 220,
    unlocked: false,
    description: 'Envelops your archer in an energy bubble that fully blocks one enemy hit.',
  },
  {
    id: 's_triple',
    name: 'Triple Volley',
    type: SpellType.TRIPLE,
    cooldown: 4,
    duration: 1,
    cost: 300,
    unlocked: false,
    description: 'Split shot. Shoots three projectiles in a wide fan-shape to blanket the battlefield.',
  },
];

export const CAMPAIGN_LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'First Blood',
    environment: EnvironmentType.GREEN_FIELDS,
    enemyCount: 2,
    enemyTypes: ['archer', 'archer'],
    rewardCoins: 40,
    description: 'Practice your aiming skills against simple archers in the serene Green Fields.',
  },
  {
    id: 2,
    name: 'Spear Shield Combat',
    environment: EnvironmentType.GREEN_FIELDS,
    enemyCount: 3,
    enemyTypes: ['archer', 'shieldman', 'archer'],
    rewardCoins: 60,
    description: 'An enemy is holding a shield. Aim for their head or legs to bypass their protection!',
  },
  {
    id: 3,
    name: 'Orc Vanguard',
    environment: EnvironmentType.ORCS_WOODS,
    enemyCount: 4,
    enemyTypes: ['spearman', 'shieldman', 'spearman', 'archer'],
    rewardCoins: 90,
    description: 'The wood thickens. Watch out for spearmen! Their heavy spears fall in extreme arcs.',
  },
  {
    id: 4,
    name: 'Shaman Magic',
    environment: EnvironmentType.ORCS_WOODS,
    enemyCount: 4,
    enemyTypes: ['archer', 'wizard', 'shieldman', 'wizard'],
    rewardCoins: 120,
    description: 'Enemy shamans join the battle, shielding allies and firing seeking lightning balls!',
  },
  {
    id: 5,
    name: 'Warlord Grok',
    environment: EnvironmentType.ORCS_WOODS,
    enemyCount: 1,
    enemyTypes: ['boss'],
    bossName: 'Warlord Grok',
    rewardCoins: 200,
    description: 'BOSS STAGE! Face Warlord Grok. He has a massive war armor, helmet, and throws axes!',
  },
  {
    id: 6,
    name: 'Volcanic Edge',
    environment: EnvironmentType.LAVA_LANDS,
    enemyCount: 5,
    enemyTypes: ['spearman', 'shieldman', 'archer', 'wizard', 'archer'],
    rewardCoins: 160,
    description: 'Step into the Lava Lands. The atmosphere is dense. Platforms hover above molten rock!',
  },
  {
    id: 7,
    name: 'Twin Slayers',
    environment: EnvironmentType.LAVA_LANDS,
    enemyCount: 6,
    enemyTypes: ['shieldman', 'spearman', 'wizard', 'spearman', 'wizard', 'archer'],
    rewardCoins: 220,
    description: 'Swarms of advanced orc guards with high iron helmets and magic shields.',
  },
  {
    id: 8,
    name: 'The Lava Golem',
    environment: EnvironmentType.LAVA_LANDS,
    enemyCount: 1,
    enemyTypes: ['boss'],
    bossName: 'Cinder, Lava Golem',
    rewardCoins: 400,
    description: 'BOSS STAGE! Slay the giant Fire Golem. He fires multi-magma bursts and has 500 HP!',
  },
];
